PerfectBabysitter/Controllers/ApplicantController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using PerfectBabysitter.Models;
using PerfectBabysitter.Models.ViewModels;
using System.Diagnostics;

namespace PerfectBabysitter.Controllers
{
    public class ApplicantController : Controller
    {
        private IAppliedJobRepository repository;
        //add repo/db for Applicant/Account

        public ApplicantController(IAppliedJobRepository repo)
        {
            repository = repo;
        }
        
        public ActionResult Applicant()
        {
            return View(repository.AppliedJobs);
        }

        public ViewResult ApplicantList() 
        {
            return View("~/Views/ApplicantList/ApplicantList.cshtml", repository.AppliedJobs);
        }

        public ViewResult AppliedJobs() 
        {
            return View("~/Views/Applicant/AppliedJobs.cshtml", repository.AppliedJobs);
        }

        [HttpPost]
        public ActionResult Applicant(int jobId, string status)
        {
            AppliedJob aJob = repository.AppliedJobs.FirstOrDefault(j => j.Id == jobId);
            repository.UpdateStatus(aJob, status);
            return View(repository.AppliedJobs);
        }

        [HttpPost]
        public ActionResult AppliedJobs(int jobId, string status)
        {
            AppliedJob aJob = repository.AppliedJobs.FirstOrDefault(j => j.Id == jobId);
            repository.UpdateAppliedStatus(aJob, status);
            return View(repository.AppliedJobs);
        }

        public ActionResult Details(int Id)  
        {  
            
           AppliedJob info = new AppliedJob();
           info = repository.AppliedJobs.Where(r => r.Id == Id).FirstOrDefault();
            return PartialView("ApplicantDetails", info);
        }


       

    }
}

PerfectBabysitter/Controllers/PostJobController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore.Diagnostics;
using PerfectBabysitter.Models;
using PerfectBabysitter.Models.ViewModels;
using Microsoft.EntityFrameworkCore.Update;
using Microsoft.AspNetCore.Authorization;

namespace PerfectBabysitter.Controllers
{
    public class PostJobController : Controller
    {

        private IJobPostingsRepository repository;

        public PostJobController(IJobPostingsRepository repo)
        {
            repository = repo;
        }
        [Authorize]
        [HttpGet]
        public ViewResult JobForm()
        {
            JobPosting job = new JobPosting();
            return View(job);
        }

        [Authorize]
        [HttpPost]
        public ActionResult JobForm(JobPosting job)
        {
            if (ModelState.IsValid)
            {
                return RedirectToAction(nameof(CompletedForm));
            }

            return View(job);
        }
        [Authorize]
        [HttpGet]
        public ActionResult Edit(int id)
        {
            JobPosting posting = repository.GetJobPosting(id);
            JobsListEditViewModel job = new JobsListEditViewModel
            {
                Id = posting.Id,
                JobTitle = posting.JobTitle,
                PhoneNumber = posting.PhoneNumber,
                Email = posting.Email,
                Address = posting.Address,
                Children = posting.Children,
                Date = posting.Date,
                DatePosted = posting.DatePosted,
                StartTime = posting.StartTime,
                EndTime = posting.EndTime,
                Language = posting.Language,
                Cooking = posting.Cooking,
                Cleaning = posting.Cleaning,
                Activities = posting.Activities,
                Description = posting.Description

            };
            return View(job);
        }

        [HttpPost]
        public ActionResult Edit(JobPosting model)
        {
            if (ModelState.IsValid)
            {
                var posting = repository.GetJobPosting(model.Id);
                posting.Id = model.Id;
                posting.JobTitle = model.JobTitle;
                posting.PhoneNumber = model.PhoneNumber;
                posting.Email = model.Email;
                posting.Address = model.Address;
                posting.Children = model.Children;
                posting.Date = model.Date;
                posting.DatePosted = model.DatePosted;
                posting.StartTime = model.StartTime;
                posting.EndTime = model.EndTime;
                posting.Language = model.Language;
                posting.Cooking = model.Cooking;
                posting.Cleaning = model.Cleaning;
                posting.Activities = model.Activities;
                posting.Description = model.Description;
            }
            JobPosting updatePosting = repository.Update(model);
            return RedirectToAction(nameof(CompletedEdit));
        }

        public ViewResult CompletedEdit()
        {
            ViewBag.CompleteMessage = "Your posting has been successfully updated!";
            return View();
        }
        public ViewResult CompletedForm()
        {
            ViewBag.CompleteMessage = "Your job posting has been uploaded!";
            return View();
        }
        [Authorize]
        public ActionResult ViewJobs()
        {
            return View("ViewJobs", repository.JobPostings);
        }
        [Authorize]
        public ViewResult PostedJobs()
        {
            return View("PostedJobs", repository.JobPostings);
        }
    }
}

PerfectBabysitter/Controllers/SearchController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using PerfectBabysitter.Models;
using PerfectBabysitter.Models.ViewModels;
using System.Diagnostics;

namespace PerfectBabysitter.Controllers
{
    public class SearchController : Controller
    {
        private IJobPostingsRepository repository;
        public SearchController(IJobPostingsRepository repo)
        {
            repository = repo;
        }
        [HttpGet]
        public ViewResult SearchAddress(string address)
        {

            ViewBag.Title = "Search Results";
            var results = from jobs in repository.JobPostings select jobs;
            if (!string.IsNullOrEmpty(address))
            {
                results = results.Where(r => r.Address.Contains(address));
            }
            else
            {
                results = results.OrderBy(r => r.Id);
            }
            JobsListViewModel jobListVM = new JobsListViewModel();
            jobListVM.JobPostings = results;
            jobListVM.Address = address;
            return View("SearchResults", jobListVM);

        }

        [HttpGet]
        public ViewResult SearchResults(string address, int children, bool householdDuties, bool cooking, bool cleaning, string activities)
        {

            ViewBag.Title = "Search Results";
            var results = from jobs in repository.JobPostings select jobs;
            if (!string.IsNullOrEmpty(address))
            {
                results = results.Where(r => r.Address.Contains(address));
            }
            if (!string.IsNullOrEmpty(children.ToString()) || children >= 1)
            {
                results = results.Where(r => r.Children <= children);
            }

            if (householdDuties != null && householdDuties == true)
            {
                if (!string.IsNullOrEmpty(cooking.ToString()))
                {
                    results = results.Where(r => r.Cooking == cooking);
                }
                if (!string.IsNullOrEmpty(cleaning.ToString()))
                {
                    results = results.Where(r => r.Cleaning == cleaning);
                }
            }
            else if (householdDuties != null && householdDuties == false)
            {
                results = results.Where(r => r.Cleaning == false && r.Cooking == false);
            }

            if (!string.IsNullOrEmpty(activities))
            {
                results = results.Where(r => r.Activities.Contains(activities));
            }
            JobsListViewModel jobListVM = new JobsListViewModel();
            jobListVM.JobPostings = results;
            jobListVM.Address = address;
            jobListVM.Children = children.ToString();
            jobListVM.Cooking = cooking;
            jobListVM.Cleaning = cleaning;
            jobListVM.Activities = activities;
            return View("SearchResults", jobListVM);

        }

        [HttpGet]
        public ViewResult JobDetails(int jobId)
        {
            JobPosting JobPosting = repository.JobPostings.Where(r => r.Id == jobId).FirstOrDefault();
            return View(JobPosting);
        }
    }
}

PerfectBabysitter/Views/Shared/JobSummary.cshtml
@model JobPosting

<h4>
    @Model.JobTitle
</h4>
<p>
    @Model.Description
</p>
<a asp-action="JobDetails" asp-controller="Search" asp-route-jobId="@Model.Id">
    See Details
</a>

PerfectBabysitter/Views/Shared/_BabysitterLayout.cshtml
@if (IsSectionDefined("scripts"))
{
    RenderSection("scripts");
}

@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@ViewBag.Title</title>
    <!-- Bootstrap core CSS -->

    <link href="~/css/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom fonts for this template -->
    <link href="~/fontawesome-free/css/all.min.css" rel="stylesheet">
    <link href="~/simple-line-icons/css/simple-line-icons.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
    <!-- Custom styles for this template -->
    <link href="~/css/landing-page.css" rel="stylesheet">
</head>
<body class="">
    <!-- Navigation -->
    <!-- Masthead -->
    <!-- Navigation -->
    <nav class="navbar navbar-light bg-light static-top">
        <div class="container">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">PerfectBabySitter</a>
            <nav class="navbar navbar-expand-lg navbar-light bg-light" style="">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="true" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse show" id="navbarSupportedContent" style="">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" asp-action="Index">Home <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Jobs", "ViewJobs", "PostJob", null, new { @class = "nav-link" })
                        </li>

                        <li class="nav-item dropdown hide">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                About us
                            </a>
                            <div class="dropdown-menu hide" aria-labelledby="navbarDropdown">
                                @Html.ActionLink("About Us", "AboutUs", "Home", null, new { @class = "dropdown-item" })
                                @Html.ActionLink("Privacy Policy", "PrivacyPolicy", "Home", null, new { @class = "dropdown-item" })
                                <div class="dropdown-divider"></div>
                                @Html.ActionLink("Contact Us", "ContactUs", "Home", null, new { @class = "dropdown-item" })
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
            @if (SignInManager.IsSignedIn(User))
            {
                @*@if (User.IsInRole("BabySitter"))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" title="Wow">This works</a>
                        </li>
                    }*@
                <li class="nav-item">
                    <a class="nav-link text-dark" title="Manage">Hello @User.Identity.Name!</a>
                </li>
                @Html.ActionLink("Log Out", "Logout", "Account", null, new { @class = "btn btn-primary" })
            }
            else
            {
                @Html.ActionLink("Sign In", "Login", "Account", null, new { @class = "btn btn-primary" })
            }
        </div>
    </nav>
    <nav class="navbar navbar-dark bg-dark static-top">
        <div class="container">

            <nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="">

                <div class="navbar-collapse collapse show" id="navbarSupportedContent" style="">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            @Html.ActionLink("   View Profile   ", "ViewJobs", "PostJob", null, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("   View Jobs   ", "ViewJobs", "PostJob", null, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("   Applied Jobs  ", "AppliedJobs", "Applicant", null, new { @class = "nav-link" })
                        </li>

                    </ul>
                </div>
            </nav>
        </div>
    </nav>
    <div>
        @RenderBody()
    </div>
</body>
<!-- Footer -->
<footer class="footer bg-light">
    <div>
        <div class="row">
            <div class="col-lg-6 h-100 text-center text-lg-left my-auto">
                <ul class="list-inline mb-2">
                    <li class="list-inline-item">
                        <a href="#">About</a>
                    </li>
                    <li class="list-inline-item">⋅</li>
                    <li class="list-inline-item">
                        <a href="#">Contact</a>
                    </li>
                    <li class="list-inline-item">⋅</li>
                    <li class="list-inline-item">
                        <a href="#">Terms of Use</a>
                    </li>
                    <li class="list-inline-item">⋅</li>
                    <li class="list-inline-item">
                        <a href="#">Privacy Policy</a>
                    </li>
                </ul>
                <p class="text-muted small mb-4 mb-lg-0">© PerfectBabySitter 2020. All Rights Reserved.</p>
            </div>
            <div class="col-lg-6 h-100 text-center text-lg-right my-auto">
                <ul class="list-inline mb-0">
                    <li class="list-inline-item mr-3">
                        <a href="#">
                            <i class="fab fa-facebook fa-2x fa-fw"></i>
                        </a>
                    </li>
                    <li class="list-inline-item mr-3">
                        <a href="#">
                            <i class="fab fa-twitter-square fa-2x fa-fw"></i>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                            <i class="fab fa-instagram fa-2x fa-fw"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>
<!-- Bootstrap core JavaScript -->
<script src="~/jquery/jquery.min.js"></script>
<script src="~/css/bootstrap/js/bootstrap.bundle.min.js"></script>



<script id="custom-js" src="~/js/code_editor_scripts.js?TruMSMHV"></script>

</html>

PerfectBabysitter/Views/Shared/_Layout.cshtml
@if (IsSectionDefined("scripts"))
{
    RenderSection("scripts");
}

@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@ViewBag.Title</title>
    <!-- Bootstrap core CSS -->

    <link href="~/css/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom fonts for this template -->
    <link href="~/fontawesome-free/css/all.min.css" rel="stylesheet">
    <link href="~/simple-line-icons/css/simple-line-icons.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
    <!-- Custom styles for this template -->
    <link href="~/css/landing-page.css" rel="stylesheet">
</head>
<body class="">
    <!-- Navigation -->
    <!-- Masthead -->
    <!-- Navigation -->
    <nav class="navbar navbar-light bg-light static-top">
        <div class="container">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">PerfectBabySitter</a>
            <nav class="navbar navbar-expand-lg navbar-light bg-light" style="">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="true" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse show" id="navbarSupportedContent" style="">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" asp-action="Index">Home <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Jobs", "ViewJobs", "PostJob", null, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Register", "Register", "Account", null, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item dropdown hide">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                About us
                            </a>
                            <div class="dropdown-menu hide" aria-labelledby="navbarDropdown">
                                @Html.ActionLink("About Us", "AboutUs", "Home", null, new { @class = "dropdown-item" })
                                @Html.ActionLink("Privacy Policy", "PrivacyPolicy", "Home", null, new { @class = "dropdown-item" })
                                <div class="dropdown-divider"></div>
                                @Html.ActionLink("Contact Us", "ContactUs", "Home", null, new { @class = "dropdown-item" })
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
            @if (SignInManager.IsSignedIn(User))
            {
                @*@if (User.IsInRole("BabySitter"))
            {
                <li class="nav-item">
                    <a class="nav-link text-dark" title="Wow">This works</a>
                </li>
            }*@
                <li class="nav-item">
                    <a class="nav-link text-dark" title="Manage">Hello @User.Identity.Name!</a>
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Profile", "Account", "Account", null, new { @class = "btn btn-primary" })
                </li>
                @Html.ActionLink("Log Out", "Logout", "Account", null, new { @class = "btn btn-primary" })
            }
            else
            {
                @Html.ActionLink("Sign In", "Login", "Account", null, new { @class = "btn btn-primary" })
            }
        </div>
    </nav>
    <div>
        @RenderBody()
    </div>
</body>
    <!-- Footer -->
    <footer class="footer bg-light">
        <div>
            <div class="row">
                <div class="col-lg-6 h-100 text-center text-lg-left my-auto">
                    <ul class="list-inline mb-2">
                        <li class="list-inline-item">
                            <a href="#">About</a>
                        </li>
                        <li class="list-inline-item">⋅</li>
                        <li class="list-inline-item">
                            <a href="#">Contact</a>
                        </li>
                        <li class="list-inline-item">⋅</li>
                        <li class="list-inline-item">
                            <a href="#">Terms of Use</a>
                        </li>
                        <li class="list-inline-item">⋅</li>
                        <li class="list-inline-item">
                            <a href="#">Privacy Policy</a>
                        </li>
                    </ul>
                    <p class="text-muted small mb-4 mb-lg-0">© PerfectBabySitter 2020. All Rights Reserved.</p>
                </div>
                <div class="col-lg-6 h-100 text-center text-lg-right my-auto">
                    <ul class="list-inline mb-0">
                        <li class="list-inline-item mr-3">
                            <a href="#">
                                <i class="fab fa-facebook fa-2x fa-fw"></i>
                            </a>
                        </li>
                        <li class="list-inline-item mr-3">
                            <a href="#">
                                <i class="fab fa-twitter-square fa-2x fa-fw"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#">
                                <i class="fab fa-instagram fa-2x fa-fw"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
    <!-- Bootstrap core JavaScript -->
    <script src="~/jquery/jquery.min.js"></script>
    <script src="~/css/bootstrap/js/bootstrap.bundle.min.js"></script>



    <script id="custom-js" src="~/js/code_editor_scripts.js?TruMSMHV"></script>

</html>

PerfectBabysitter/Views/Shared/_ParentLayout.cshtml
@if (IsSectionDefined("scripts"))
{
    RenderSection("scripts");
}

@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@ViewBag.Title</title>
    <!-- Bootstrap core CSS -->

    <link href="~/css/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom fonts for this template -->
    <link href="~/fontawesome-free/css/all.min.css" rel="stylesheet">
    <link href="~/simple-line-icons/css/simple-line-icons.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
    <!-- Custom styles for this template -->
    <link href="~/css/landing-page.css" rel="stylesheet">
</head>
<body class="">
    <!-- Navigation -->
    <!-- Masthead -->
    <!-- Navigation -->
    <nav class="navbar navbar-light bg-light static-top">
        <div class="container">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">PerfectBabySitter</a>
            <nav class="navbar navbar-expand-lg navbar-light bg-light" style="">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="true" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse show" id="navbarSupportedContent" style="">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-action="Index">Home <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Jobs", "ViewJobs", "PostJob", null, new { @class = "nav-link" })
                        </li>

                        <li class="nav-item dropdown hide">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                About us
                            </a>
                            <div class="dropdown-menu hide" aria-labelledby="navbarDropdown">
                                @Html.ActionLink("About Us", "AboutUs", "Home", null, new { @class = "dropdown-item" })
                                @Html.ActionLink("Privacy Policy", "PrivacyPolicy", "Home", null, new { @class = "dropdown-item" })
                                <div class="dropdown-divider"></div>
                                @Html.ActionLink("Contact Us", "ContactUs", "Home", null, new { @class = "dropdown-item" })
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
            @if (SignInManager.IsSignedIn(User))
            {
                @*@if (User.IsInRole("BabySitter"))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" title="Wow">This works</a>
                        </li>
                    }*@
                <li class="nav-item">
                    <a class="nav-link text-dark" title="Manage">Hello @User.Identity.Name!</a>
                </li>
                @Html.ActionLink("Log Out", "Logout", "Account", null, new { @class = "btn btn-primary" })
            }
            else
            {
                @Html.ActionLink("Sign In", "Login", "Account", null, new { @class = "btn btn-primary" })
            }
        </div>
    </nav>
    <nav class="navbar navbar-dark bg-dark static-top">
        <div class="container">

            <nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="">

                <div class="navbar-collapse collapse show" id="navbarSupportedContent" style="">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item ">
                            @Html.ActionLink("   View Profile   ", "ViewJobs", "PostJob", null, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("   Post Job   ", "JobForm", "PostJob", null, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("   Applicant List   ", "ApplicantList", "ApplicantList", null, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("   Applicant List   ", "ApplicantList", "ApplicantList", null, new { @class = "nav-link" })
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </nav>
    <div>
        @RenderBody()
    </div>
</body>
<!-- Footer -->
<footer class="footer bg-light">
    <div>
        <div class="row">
            <div class="col-lg-6 h-100 text-center text-lg-left my-auto">
                <ul class="list-inline mb-2">
                    <li class="list-inline-item">
                        <a href="#">About</a>
                    </li>
                    <li class="list-inline-item">⋅</li>
                    <li class="list-inline-item">
                        <a href="#">Contact</a>
                    </li>
                    <li class="list-inline-item">⋅</li>
                    <li class="list-inline-item">
                        <a href="#">Terms of Use</a>
                    </li>
                    <li class="list-inline-item">⋅</li>
                    <li class="list-inline-item">
                        <a href="#">Privacy Policy</a>
                    </li>
                </ul>
                <p class="text-muted small mb-4 mb-lg-0">© PerfectBabySitter 2020. All Rights Reserved.</p>
            </div>
            <div class="col-lg-6 h-100 text-center text-lg-right my-auto">
                <ul class="list-inline mb-0">
                    <li class="list-inline-item mr-3">
                        <a href="#">
                            <i class="fab fa-facebook fa-2x fa-fw"></i>
                        </a>
                    </li>
                    <li class="list-inline-item mr-3">
                        <a href="#">
                            <i class="fab fa-twitter-square fa-2x fa-fw"></i>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                            <i class="fab fa-instagram fa-2x fa-fw"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>
<!-- Bootstrap core JavaScript -->
<script src="~/jquery/jquery.min.js"></script>
<script src="~/css/bootstrap/js/bootstrap.bundle.min.js"></script>



<script id="custom-js" src="~/js/code_editor_scripts.js?TruMSMHV"></script>

</html>